@props(['src', 'alt' => '', 'class' => ''])

@php
    // Basic logic to assume original images might have avif/webp versions available
    // In a real system, these would be generated by a media library like Spatie Media Library
    $info = pathinfo($src);
    $base = $info['dirname'] . '/' . $info['filename'];
    $ext = $info['extension'];
@endphp

<picture class="{{ $class }}">
    {{-- AVIF: Smallest, best quality --}}
    <source srcset="{{ $base }}.avif" type="image/avif">
    {{-- WebP: Standard modern format --}}
    <source srcset="{{ $base }}.webp" type="image/webp">
    {{-- Fallback: Original format --}}
    <img src="{{ $src }}" alt="{{ $alt }}" class="{{ $class }}" loading="lazy">
</picture>
